Vagrant.configure("2") do |config|
  config.vm.box = "gusztavvargadr/visual-studio"
  config.vm.provider "hyperv"  
  config.vm.network "public_network"

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "hyperv" do |h|
    h.linked_clone = true
    h.cpus = 4
    h.maxmemory = 32768    
  end

  config.vm.provision "shell", path: "shell/InstallChocolatey.ps1"
  config.vm.provision "shell", path: "shell/InstallBoxStarter.ps1"
  config.vm.provision "shell", path: "shell/BoxStarter.ps1"  
end 

 